use CLIENTES;

INSERT INTO PROVINCIAS (PRO_NOMBRE) VALUES
("Buenos Aires"),
("Buenos Aires-GBA"),
("Capital Federal"),
("Catamarca"),
("Chaco"),
("Chubut"),
("Córdoba"),
("Corrientes"),
("Entre Ríos"),
("Formosa"),
("Jujuy"),
("La Pampa"),
("La Rioja"),
("Mendoza"),
("Misiones"),
("Neuquén"),
("Río Negro"),
("Salta"),
("San Juan"),
("San Luis"),
("Santa Cruz"),
("Santa Fe"),
("Santiago del Estero"),
("Tierra del Fuego"),
("Tucumán");

INSERT INTO LOCALIDADES (LOC_NOMBRE,LOC_PRO_ID) VALUES
('25 de Mayo',1),
('3 de febrero',1),
('A. Alsina',1),
('A. Gonzáles Cháves',1),
('Aguas Verdes',1),
('Alberti',1),
('Arrecifes',1),
('Ayacucho',1),
('Azul',1),
('Bahía Blanca',1),
('Balcarce',1);
INSERT INTO LOCALIDADES (LOC_NOMBRE,LOC_PRO_ID) VALUES
('Rawson', 6),
('Trelew', 6),
('Puerto Madryn', 6),
('Comodoro Rivadavia', 6),
('Esquel', 6),
('Gaiman', 6),
('Dolavon', 6),
('Trevelin', 6),
('El Hoyo', 6),
('Lago Puelo', 6),
('Epuyén', 6),
('Cholila', 6),
('Camarones', 6),
('Sarmiento', 6),
('Rada Tilly', 6),
('Río Mayo', 6),
('Tecka', 6),
('Corcovado', 6),
('Gualjaina', 6),
('José de San Martín', 6),
('Cushamen', 6),
('El Maitén', 6),
('Cerro Centinela', 6),
('Aldea Apeleg', 6),
('Aldea Beleiro', 6),
('Aldea Epulef', 6),
('Alto Río Senguer', 6),
('Buenos Aires Chico', 6),
('Colan Conhué', 6),
('Diadema Argentina', 6),
('Doctor Ricardo Rojas', 6),
('El Escorial', 6),
('El Mirasol', 6),
('El Molle', 6),
('El Sombrero', 6),
('Facundo', 6),
('Gan Gan', 6),
('Garayalde', 6),
('Gastre', 6),
('Gobernador Costa', 6),
('Las Plumas', 6),
('Leleque', 6),
('Los Altares', 6),
('Paso de los Indios', 6),
('Paso del Sapo', 6),
('Paso Flores', 6),
('Playa Unión', 6),
('Puerto Pirámides', 6),
('Río Pico', 6),
('Río Senguer', 6),
('Telsen', 6),
('Aldea San Antonio', 6),
('Dique Florentino Ameghino', 6),
('Aldea Escolar', 6),
('Aldea San Miguel', 6),
('Aldea San Rafael', 6),
('Aldea Las Pampas', 6),
('Cerro Dragon', 6),
('El Foyel', 6),
('Lago Blanco', 6),
('Lago Rosario', 6),
('Lago Vintter', 6),
('Lepá', 6),
('Paso del Carril', 6),
('Paso del Diablo', 6),
('Río Blanco', 6),
('Río Mayo Arriba', 6),
('Río Pico Norte', 6),
('El Maitén Norte', 6),
('Cerro Radal', 6),
('Futaleufú', 6),
('Las Golondrinas', 6),
('Lago Epuyén', 6),
('Río Corintos', 6),
('Río Chico', 6),
('Río Villegas', 6),
('El Corcovado', 6),
('Lago Futalaufquen', 6),
('Lago Menéndez', 6),
('El Bolsón', 6),
('San Carlos de Bariloche', 6),
('Villa La Angostura', 6),
('Junín de los Andes', 6),
('San Martín de los Andes', 6),
('Cholila', 6),
('El Hoyo', 6),
('Lago Puelo', 6),
('El Maitén', 6),
('Trevelin', 6);

INSERT INTO LOCALIDADES (LOC_NOMBRE,LOC_PRO_ID) VALUES
('San Salvador de Jujuy', 11),
('La Quiaca', 11),
('Abra Pampa', 11),
('El Carmen', 11),
('Tilcara', 11),
('Humahuaca', 11),
('Libertador General San Martín', 11),
('Perico', 11),
('Palpalá', 11),
('San Pedro de Jujuy', 11),
('La Mendieta', 11),
('Volcán', 11),
('Caimancito', 11),
('Yuto', 11),
('Maimará', 11),
('La Esperanza', 11),
('Purmamarca', 11),
('Fraile Pintado', 11),
('Calilegua', 11),
('Santa Catalina', 11),
('Vinalito', 11),
('Puesto del Marqués', 11),
('San Antonio', 11),
('León', 11),
('La Redonda', 11),
('El Aguilar', 11),
('El Talar', 11),
('San Francisco', 11),
('Barrios', 11),
('Arrayanal', 11),
('Caspala', 11),
('La Intermedia', 11),
('San Juan de Oro', 11),
('Mina Pirquitas', 11),
('Cusi Cusi', 11),
('Tumbaya', 11),
('Tunalito', 11),
('Tres Cruces', 11),
('Pampichuela', 11),
('Valle Grande', 11),
('Termas de Reyes', 11),
('Pumahuasi', 11),
('Chalican', 11),
('La Ciénaga', 11),
('La Almona', 11),
('Puesto del Marques', 11),
('Cangrejillos', 11),
('Cangrejos', 11),
('Valle Colorado', 11),
('San Pablo de Reyes', 11),
('Villa Jardín de Reyes', 11),
('Cieneguillas', 11),
('El Fuerte', 11),
('El Moreno', 11),
('Ingenio La Esperanza', 11),
('Ingenio Ledesma', 11),
('La Mina', 11),
('Puesto Viejo', 11),
('Rodeitos', 11),
('Santa Ana', 11),
('Santa Clara', 11),
('Talapampa', 11),
('Yala', 11),
('Bárcena', 11),
('Chorrillos', 11),
('La Granja', 11),
('Los Nogales', 11),
('Monterrico', 11),
('San Juan', 11),
('San Rafael', 11),
('Sausalito', 11),
('Tres Cruces Estación', 11),
('Villa Gorriti', 11),
('Villa Jardín América', 11),
('Yaví', 11),
('Churcal', 11),
('Lagunilla', 11),
('Ocloyas', 11),
('Puesto del Marqués (Río Perico)', 11),
('San Antonio de los Cobres', 11),
('Sañogasta', 11),
('Las Pampitas', 11);

INSERT INTO LOCALIDADES (LOC_NOMBRE,LOC_PRO_ID) VALUES
('Rosario', 22),
('Santa Fe', 22),
('Venado Tuerto', 22),
('Rafaela', 22),
('Santo Tomé', 22),
('Esperanza', 22),
('Reconquista', 22),
('Funes', 22),
('Granadero Baigorria', 22),
('San Lorenzo', 22),
('Villa Constitución', 22),
('Casilda', 22),
('Capitán Bermúdez', 22),
('Gálvez', 22),
('Villa Gobernador Gálvez', 22),
('Pérez', 22),
('Arroyo Seco', 22),
('Fray Luis Beltrán', 22),
('Coronda', 22),
('San Javier', 22),
('San Jorge', 22),
('Roldán', 22),
('Carcaraná', 22),
('Helvecia', 22),
('Puerto General San Martín', 22),
('Sunchales', 22),
('Firmat', 22),
('Tostado', 22),
('Villa Eloísa', 22),
('Villa Ocampo', 22),
('San Cristóbal', 22),
('Las Toscas', 22),
('San Justo', 22),
('San Carlos Centro', 22),
('Arocena', 22),
('Gobernador Crespo', 22),
('Coronel Arnold', 22),
('Franck', 22),
('Casas', 22),
('San Agustín', 22),
('San Genaro', 22),
('El Trébol', 22),
('Maciel', 22),
('Alcorta', 22),
('Álvarez', 22),
('Suardi', 22),
('Totoras', 22),
('San Jorge Norte', 22),
('Ricardone', 22),
('Arequito', 22),
('Pilar', 22),
('Tortugas', 22),
('Barrancas', 22),
('Carlos Pellegrini', 22),
('Villa Minetti', 22),
('Monte Vera', 22),
('Fighiera', 22),
('Monte Oscuridad', 22),
('Bella Italia', 22),
('Elisa', 22),
('Pavón', 22),
('Godeken', 22),
('Santo Domingo', 22),
('Sastre', 22),
('Clason', 22),
('Timbúes', 22),
('Elortondo', 22),
('Sauce Viejo', 22),
('Ramona', 22),
('Arrufó', 22),
('Maggiolo', 22),
('Humboldt', 22),
('Alejandra', 22),
('Murphy', 22),
('Empalme San Carlos', 22),
('Amenábar', 22),
('Laguna Paiva', 22),
('Santa Clara de Saguier', 22),
('María Juana', 22),
('Sancti Spiritu', 22),
('Gato Colorado', 22),
('Santa Rosa de Calchines', 22),
('Tostado', 22);




INSERT INTO CLIENTES (CLI_ID, CLI_NOMBRE, CLI_APELLIDO, CLI_CUIT, CLI_DIRECCION, CLI_LOC_ID, CLI_RAZONSOC)
VALUES 
    (1, 'Juan', 'Pérez', '20123456789', 'Calle Falsa 123', '1', 'Compañía A'),
    (2, 'María', 'García', '27345678901', 'Avenida Siempreviva 742', '1', 'Compañía B'),
    (3, 'Pedro', 'González', '23987654321', 'Calle Falsa 456', '1', 'Compañía C'),
    (4, 'Lucía', 'Rodríguez', '30-76543210', 'Calle Real 789', '1', 'Compañía D');

UPDATE CLIENTES SET CLI_NOMBRE = 'Laura', CLI_APELLIDO = 'Fernández' WHERE CLI_ID = 2;

DELETE FROM CLIENTES WHERE CLI_ID = 3;

SELECT * FROM CLIENTES;

SELECT * FROM provincias;
SELECT * FROM LOCALIDADES;

SELECT PROVINCIAS.PRO_NOMBRE, LOCALIDADES.LOC_NOMBRE 
FROM PROVINCIAS 
JOIN LOCALIDADES ON PROVINCIAS.PRO_ID = LOCALIDADES.LOC_PRO_ID;


SELECT * FROM CLIENTES WHERE CLI_ID = 1;

